export const data = [
  {
    id: 1,
    jobRole: "Building Engineer",
    date: "Aug 17, 2022 - Sep 16, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 2,
    jobRole: "Assistant Property Manager",
    date: "Aug 16, 2022 - Sep 15, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 3,
    jobRole: "Property Manager",
    date: "Apr 1, 2022 - May 1, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 4,
    jobRole: "Assistant Property Manager",
    date: "jUL 25, 2022 - Aug 24, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 5,
    jobRole: "Assistant Property Manager",
    date: "jUL 27, 2022 - Aug 26, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 6,
    jobRole: "Building Maintenance Technician",
    date: "jUL 19, 2022 - Aug 18, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 7,
    jobRole: "Administrative Assistant",
    date: "Mar 29, 2022 - APr 28, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 8,
    jobRole: "Substitute Teacher",
    date: "Mar 30, 2022 - APr 29, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
  {
    id: 9,
    jobRole: "Java Developer",
    date: "Mar 30, 2022 - APr 29, 2022",
    location: "Durham, North Carolina",
    owner: " Ana tenorio",
    hrManager: "Ana tenorio",
    applicants: [
      {
        totalApplicants: 14,
        strongFits: 0,
        fits: 2,
        weakFits: 1,
        distortions: 3,
        incompleteApplicants: 5,
      },
    ],
  },
];
